name: Build

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: KuaYue

      - name: Checkout KasugaLibNext
        uses: actions/checkout@v4
        with:
          repository: KasugaLibGroup/KasugaLibNext
          fetch-depth: 0
          fetch-tags: true
          path: KasugaLibNext

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # This is needed to be able to run ./gradlew below
      # You can run `git update-index --chmod +x gradlew` then remove this step.
      - name: Make Gradle wrapper executable
        working-directory: KuaYue
        run: chmod +x ./gradlew

      - name: Make KasugaLibNext Gradle wrapper executable
        working-directory: KasugaLibNext
        run: chmod +x ./gradlew

      - name: Build KasugaLibNext first
        working-directory: KasugaLibNext
        run: ./gradlew build -x test --no-daemon

      - name: Build with Gradle
        working-directory: KuaYue
        run: ./gradlew clean build --no-build-cache

      - name: Upload KuaYue
        uses: actions/upload-artifact@v4
        with:
          name: KuaYue-Build
          path: KuaYue/modules/core/build/libs/*.jar

      - name: Upload KasugaLibNext
        uses: actions/upload-artifact@v4
        with:
          name: KasugaLibNext-Build
          path: KasugaLibNext/modules/core/build/libs/*.jar
